### ISSUE TITLE
Why are you so funny? 🔪

### ISSUE THREAD

**Issue by racheloveyou** [shitiomatic/shitiomatic#1]
Your code always have one or more easter egg why?
- why?
- why?
- why?
- why?

**Comment by shitiomatic** [comment]
Good question! I ask myself that question all the time too.

**Comment by racheloveyou** [comment]
Fu*k youuuu

**Comment by shitiomatic** [comment]
Awww! Let’s get married!

**Comment by racheloveyou** [comment]
🤣🤣🤣🤣🤣
